FYP_Project/Controllers/DataDemoController.cs
using FYP_Project.Models;
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Dapper;
using Dapper.Contrib.Extensions;
using FYP_Project.ViewModels;
using FYP_Project.Helpers;

namespace FYP_Project.Controllers
{
    public class DataDemoController : Controller
    {
        public IActionResult Index()
        {
            CollegeViewModel viewModel = new CollegeViewModel();

            return View("index", viewModel);
        }

        public IActionResult Edit(int ID)
        {
            CollegeViewModel viewModel = new CollegeViewModel();
            viewModel.EditableCollege = viewModel.Colleges.FirstOrDefault(x => x.CollegeID == ID);
            return View("Index", viewModel);
        }

        public IActionResult Delete(int ID)
        {
            using (var db = DbHelper.GetConnection())
            {
                College college = db.Get<College>(ID);
                if (college != null)
                    db.Delete(college);
                return RedirectToAction("Index");
            }
        }

        public IActionResult CreateUpdate(CollegeViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                using (var db = DbHelper.GetConnection())
                {
                    if (viewModel.EditableCollege.CollegeID == null)
                    {
                        viewModel.EditableCollege.CollegeID = viewModel.Colleges.Count;
                        db.Insert<College>(viewModel.EditableCollege);
                    }
                    else
                    {
                        College dbItem = db.Get<College>(viewModel.EditableCollege.CollegeID);
                        TryUpdateModelAsync<College>(dbItem, "EditableCollege");
                        db.Update<College>(dbItem);
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                return View("Index", new College());
            }
        }
    }
}

FYP_Project/Views/DataDemo/Index.cshtml
@{
    ViewData["Title"] = "Data Demo";
}
@model FYP_Project.ViewModels.CollegeViewModel
<section id="colleges">
    <div class="container" data-aos="fade-up">
        <div class="row content">
            <h1>Colleges</h1>
            <table class="table table-striped table-bordered table-hover" style="max-width: 500px;">
                <tr>
                    <td colspan="5">
                        @using (var form = Html.BeginForm("CreateUpdate", "DataDemo", FormMethod.Post))
                        {
                            @Html.HiddenFor(model => model.EditableCollege.CollegeID)
                            <div class="input-group">
                                @Html.TextBoxFor(model => model.EditableCollege.CollegeName, new { @class = "form-control", placeholder = "College Name" })
                                @Html.TextBoxFor(model => model.EditableCollege.CollegeAbbv, new { @class = "form-control", placeholder = "College Abbreviation" })
                                @Html.TextBoxFor(model => model.EditableCollege.CollegeCounty, new { @class = "form-control", placeholder = "College County" })
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-success">@(Model.EditableCollege.CollegeID > 0 ? "Update" : "Add")</button>
                                </div>
                            </div>
                            @Html.ValidationSummary()
                        }
                    </td>
                </tr>
                @foreach (var college in Model.Colleges)
                {
                    <tr>
                        <td class="text-center">
                            @college.CollegeName
                        </td>
                        <td class="text-center">
                            @college.CollegeAbbv
                        </td>
                        <td class="text-center">
                            @college.CollegeCounty
                        </td>
                        <td class="text-center">
                            <a href="/DataDemo/Edit/@college.CollegeID" onclick="return confirm('Are you sure you want to edit this college?');" class="btn btn-sm btn-success">Edit</a>
                        </td>
                        <td class="text-center">
                            <a href="/DataDemo/Delete/@college.CollegeID" onclick="return confirm('Are you sure tou want to delete this college?');" class="btn btn-sm btn-Danger">Delete</a>
                        </td>
                    </tr>
                }
            </table>
            </div>
        </div>
</section>