FYP_Project/Models/Challenge.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Dapper.Contrib.Extensions;

namespace FYP_Project.Models
{
    public class Challenge
    {

        [ExplicitKey]
        public int ChallengeID { get; set; }

        public int? TeamID { get; set; }

        public int? ChallengerTeamID { get; set; }

        public string ChallengeType { get; set; }

        public DateTime ChallengeDate { get; set; }

        public DateTime CompleteBy { get; set; }

        public int Accepted { get; set; }
    }
}

FYP_Project/ViewModels/ChallengeViewModel.cs
using System;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using System.Linq;
using FYP_Project.Models;
using Dapper;
using FYP_Project.Helpers;

namespace FYP_Project.ViewModels
{
    public class ChallengeViewModel
    {
        public ChallengeViewModel()
        {
            using (var db = DbHelper.GetConnection())
            {
                this.EditableChallenge = new Challenge();
                this.Teams = db.Query<Team>("Select * FROM Teams ORDER BY TeamID DESC").ToList();
                this.Colleges = db.Query<College>("Select * FROM Colleges ORDER BY CollegeID DESC").ToList();
                this.Players = db.Query<Player>("Select * FROM Players ORDER BY PlayerID DESC").ToList();
                this.Games = db.Query<Game>("Select * FROM Games ORDER BY GameID DESC").ToList();
                this.Results = db.Query<Result>("Select * FROM Results ORDER BY ResultID DESC").ToList();
                this.joinRequests = db.Query<JoinRequest>("Select * FROM JoinRequests ORDER BY RequestID DESC").ToList();
                this.Challenges = db.Query<Challenge>("Select * FROM Challenges ORDER BY ChallengeID DESC").ToList();
            }
        }

        public List<Team> Teams { get; set; }
        public List<College> Colleges { get; set; }
        public List<Player> Players { get; set; }
        public List<Game> Games { get; set; }
        public List<Result> Results { get; set; }
        public List<JoinRequest> joinRequests { get; set; }
        public List<Challenge> Challenges { get; set; }

        public Team EditableTeam { get; set; }
        public Player EditablePlayer { get; set; }
        public Challenge EditableChallenge { get; set; }
        public List<Team> GameTeams { get; set; }
    }
}

FYP_Project/Controllers/ChallengesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dapper.Contrib.Extensions;
using FYP_Project.ViewModels;
using FYP_Project.Models;
using FYP_Project.Helpers;
using Microsoft.AspNetCore.Http;

namespace FYP_Project.Controllers
{
    public class ChallengesController : Controller
    {
        public IActionResult Index()
        {
            string email = HttpContext.Session.GetString("emailAddress");

            ChallengeViewModel viewModel = new ChallengeViewModel();

            if (email == null)
            {
                return View("Index");
            }
            else
            {
                foreach (var player in viewModel.Players)
                {
                    if (email == player.emailAddress)
                    {
                        viewModel.EditablePlayer = player;
                    }
                }
                return View("Index", viewModel);
            }
        }

        public IActionResult Challenges()
        {
            string email = HttpContext.Session.GetString("emailAddress");

            ChallengeViewModel viewModel = new ChallengeViewModel();

            if (email == null)
            {
                return View("Index");
            }
            else
            {
                foreach (var player in viewModel.Players)
                {
                    if (email == player.emailAddress)
                    {
                        viewModel.EditablePlayer = player;
                    }
                }
                return View("ChallengeTeam", viewModel);
            }
        }

        public IActionResult Create(ChallengeViewModel viewModel)
        {
            string email = HttpContext.Session.GetString("emailAddress");
            foreach (var player in viewModel.Players)
            {
                if (email == player.emailAddress)
                {
                    viewModel.EditablePlayer = player;
                }
            }

            string TeamName = Request.Form["TeamName"].ToString();
            string ChallengeType = Request.Form["ChallengeType"].ToString();
            string Amount = Request.Form["Amount"].ToString();
            ChallengeType = ChallengeType.Replace('x', char.Parse(Amount));
            using (var db = DbHelper.GetConnection())
            {
                viewModel.EditableChallenge.ChallengeID = viewModel.Challenges.Count;
                viewModel.EditableChallenge.ChallengerTeamID = viewModel.EditablePlayer.TeamID;
                viewModel.EditableChallenge.ChallengeType = ChallengeType;
                viewModel.EditableChallenge.ChallengeDate = System.DateTime.Now;
                viewModel.EditableChallenge.Accepted = 0;
                foreach(var team in viewModel.Teams)
                {
                    if(team.TeamName == TeamName)
                    {
                        viewModel.EditableChallenge.TeamID = team.TeamID;
                    }
                }
                db.Insert<Challenge>(viewModel.EditableChallenge);
            }

            if (email == null)
            {
                return View("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }          
        }

        public IActionResult Accept(int ID)
        {
            ChallengeViewModel viewModel = new ChallengeViewModel();
            using (var db = DbHelper.GetConnection())
            {
                foreach (var challenge in viewModel.Challenges)
                {
                    if (challenge.ChallengeID == ID)
                    {
                        viewModel.EditableChallenge = challenge;
                        viewModel.EditableChallenge.Accepted = 1;
                        Challenge dbItem = db.Get<Challenge>(viewModel.EditableChallenge.ChallengeID);
                        TryUpdateModelAsync<Challenge>(dbItem, "EditableChallenge");
                        db.Update<Challenge>(viewModel.EditableChallenge);
                    }
                }
            }
            string email = HttpContext.Session.GetString("emailAddress");
            if (email == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                foreach (var player in viewModel.Players)
                {
                    if (email == player.emailAddress)
                    {
                        viewModel.EditablePlayer = player;
                    }
                }
                return View("Index", viewModel);
            }
        }

        public IActionResult Decline(int ID)
        {
            ChallengeViewModel viewModel = new ChallengeViewModel();
            using (var db = DbHelper.GetConnection())
            {
                foreach (var challenge in viewModel.Challenges)
                {
                    if (challenge.ChallengeID == ID)
                    {
                        viewModel.EditableChallenge = challenge;
                        viewModel.EditableChallenge.Accepted = 2;
                        Challenge dbItem = db.Get<Challenge>(viewModel.EditableChallenge.ChallengeID);
                        TryUpdateModelAsync<Challenge>(dbItem, "EditableChallenge");
                        db.Update<Challenge>(viewModel.EditableChallenge);
                    }
                }
            }
            string email = HttpContext.Session.GetString("emailAddress");
            if (email == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                foreach (var player in viewModel.Players)
                {
                    if (email == player.emailAddress)
                    {
                        viewModel.EditablePlayer = player;
                    }
                }
                return View("Index", viewModel);
            }
        }
    }
}

FYP_Project/Views/Challenges/ChallengeTeam.cshtml
@model FYP_Project.ViewModels.ChallengeViewModel
@{
    ViewData["Title"] = "Create Challenge";
    List<string> TeamNames = new List<string>();
    List<int> Count = new List<int>();
    for(int i = 1; i <= 9; i++)
    {
        Count.Add(i);
    }
    int GameID = 0;
    foreach (var team in Model.Teams)
    {
        if (team.TeamID == Model.EditablePlayer.TeamID)
        {
            GameID = team.GameID;
            ViewBag.GameID = GameID;
        }
    }
    foreach (var team in Model.Teams)
    {
        if (team.GameID == GameID)
        {
            TeamNames.Add(team.TeamName);
        }
    }
    TeamNames = TeamNames.OrderBy(team => team).ToList();
}
<!-- code for register page found here: https://startbootstrap.com/snippets/registration-page -->

<section id="services" class="services section-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-xl-9 mx-auto">
                <div class="card flex-row my-5 border-0 shadow rounded-3 overflow-hidden">
                    <div class="card-img-left d-none d-md-flex">
                        <!-- Background image for card set in CSS! -->
                    </div>
                    <div class="card-body p-4 p-sm-5">
                        <h5 class="card-title text-center mb-5 fw-light fs-5">Create Challenge</h5>

                        @using (var form = Html.BeginForm("Create", "Challenges", FormMethod.Post))
                        {
                            @Html.HiddenFor(model => model.EditableChallenge.ChallengeID)
                            @Html.HiddenFor(model => model.EditableChallenge.TeamID)
                            @Html.HiddenFor(model => model.EditableChallenge.ChallengerTeamID)
                            @Html.HiddenFor(model => model.EditableChallenge.ChallengeDate)
                            @Html.HiddenFor(model => model.EditableChallenge.Accepted)
                            @Html.HiddenFor(model => model.EditableChallenge.ChallengeType)


                            <div class="form-floating mb-3">
                                @Html.DropDownList("TeamName", new SelectList(TeamNames), new { @class = "form-control", placeholder = "Team to Challenge" })
                                <label for="floatingInputUsername">Team to Challenge</label>
                            </div>

                            @if (GameID == 0)
                            {
                                <div class="form-floating mb-3">
                                    @Html.DropDownList("ChallengeType", new List<SelectListItem> { new SelectListItem { Value = "Score x Goals", Text = "Score x Goals" }, new SelectListItem { Value = "Assist x Goals", Text = "Assist x Goals" }, new SelectListItem { Value = "Save x Goals", Text = "Save x Goals" }, new SelectListItem { Value = "Demo x Players", Text = "Demo x Players" } }, new { @class = "form-control", placeholder = "Challenge Type" })
                                    <label for="floatingInputUsername">Challenge Type</label>
                                </div>
                            }
                            else
                            {
                                <div class="form-floating mb-3">
                                    @Html.DropDownList("ChallengeType", new List<SelectListItem> { new SelectListItem { Value = "Kill x Players", Text = "kill x Players" }, new SelectListItem { Value = "Assist x Kills", Text = "Assist x Kills" }, new SelectListItem { Value = "Win x Matches", Text = "Win x Matches" }}, new { @class = "form-control", placeholder = "Challenge Type" })
                                    <label for="floatingInputUsername">Challenge Type</label>
                                </div>
                            }
                            <div class="form-floating mb-3">
                                @Html.DropDownList("Amount", new SelectList(Count), new { @class = "form-control", placeholder = "Amount for Selected Challenge:" })
                                <label for="floatingInputUsername">Amount for Selected Challenge:</label>
                            </div>

                            <label for="floatingInputUsername">Complete By:</label>
                            <div class="form-floating mb-3">
                                @Html.EditorFor(model => model.EditableChallenge.CompleteBy, new { @class = "form-control", placeholder = "Match Date", Value = System.DateTime.Today })
                            </div>

                            <div class="d-grid mb-2">
                                <button class="btn btn-lg btn-primary btn-login fw-bold text-uppercase" type="submit">Create Challenge</button>
                            </div>

                            @Html.ValidationSummary()
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <link rel="stylesheet" type="text/css" href="~/css/LogIn.css" />

</section>

FYP_Project/Views/Challenges/Index.cshtml
@{
    ViewData["Title"] = "Challenges";
    int i = 1;
    int j = 1;
}
@model FYP_Project.ViewModels.ChallengeViewModel

<section id="services" class="services section-bg">
    <div class="container" data-aos="fade-up">

        <div class="section-title" data-aos="fade-up">
            <h2>Challenges From Rival Teams</h2>
        </div>

        <div class=" text-center">
            <div class="text-center"><a asp-controller=Challenges asp-action=Challenges class="btn-get-started">Challenge Rival</a></div>
        </div>

        <table id="ChallengesRecievedTable" class="display" style="width:100%">
            <thead>
                <tr>
                    <th>Challenge #</th>
                    <th>Challenge Type</th>
                    <th>From</th>
                    <th>Complete By</th>
                    <th>Response</th>
                </tr>
            </thead>
            <tbody class="requestsTableBody">
                @foreach (var challenge in Model.Challenges)
                {
                    if (challenge.TeamID == Model.EditablePlayer.TeamID)
                    {
                <tr>
                    <td>#@i</td>
                    <td>@challenge.ChallengeType</td>
                    @foreach (var team in Model.Teams)
                    {
                        if (team.TeamID == challenge.ChallengerTeamID)
                        {
                            <td>@team.TeamName</td>
                        }
                    }
                    <td>@challenge.CompleteBy.Day/@challenge.CompleteBy.Month/@challenge.CompleteBy.Year</td>
                    @if (challenge.Accepted == 0)
                    {
                        <td><a href="/Challenges/Accept/@challenge.ChallengeID" class="btn btn-sm btn-success">Accept</a>     <a href="/Challenges/Decline/@challenge.ChallengeID" class="btn btn-sm btn-success">Decline</a></td>
                    }
                    else if (challenge.Accepted == 1)
                    {
                        <td>Challenge in Progress</td>
                    }
                    else
                    {
                        <td>Challenge Declined</td>
                    }
                </tr>
                        i++;
                    }
                }

            </tbody>
        </table>

    </div>

    <!-- Datatable syling and functionality https://datatables.net/manual/installation -->
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>

    <link rel="stylesheet" type="text/css" href="~/DataTables/datatables.css" />

    <script type="text/javascript" src="~/DataTables/datatables.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#ChallengesRecievedTable').DataTable();
        });
    </script>

</section>

<section id="services" class="services section-bg">
    <div class="container" data-aos="fade-up">

        <div class="section-title" data-aos="fade-up">
            <h2>Challenges Sent to Rival Teams</h2>
        </div>

        <table id="ChallengesSentTable" class="display" style="width:100%">
            <thead>
                <tr>
                    <th>Challenge #</th>
                    <th>Challenge Type</th>
                    <th>Sent To</th>
                    <th>Complete By</th>
                    <th>Response</th>
                </tr>
            </thead>
            <tbody class="requestsTableBody">
                @foreach (var challenge in Model.Challenges)
                {
                    if (challenge.ChallengerTeamID == Model.EditablePlayer.TeamID)
                    {
                <tr>
                    <td>#@j</td>
                    <td>@challenge.ChallengeType</td>
                    @foreach (var team in Model.Teams)
                    {
                        if (team.TeamID == challenge.TeamID)
                        {
                            <td>@team.TeamName</td>
                        }
                    }
                    <td>@challenge.CompleteBy.Day/@challenge.CompleteBy.Month/@challenge.CompleteBy.Year</td>
                    @if (challenge.Accepted == 0)
                    {
                        <td>Waiting For Response</td>
                    }
                    else if (challenge.Accepted == 1)
                    {
                        <td>Challenge Accepted</td>
                    }
                    else
                    {
                        <td>Challenge Declined</td>
                    }
                </tr>
                        j++;
                    }
                }

            </tbody>
        </table>

    </div>

    <script>
        $(document).ready(function () {
            $('#ChallengesSentTable').DataTable();
        });
    </script>

</section>