FYP_Project/Controllers/LogInController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Dapper.Contrib.Extensions;
using FYP_Project.ViewModels;
using FYP_Project.Helpers;
using FYP_Project.Models;
/* Code to hash password found here: https://jasonwatmore.com/post/2020/07/16/aspnet-core-3-hash-and-verify-passwords-with-bcrypt?fbclid=IwAR25zwXUqLc-P2SSsXzHgI3nOv86eoCQHLlRV0SCgNYvqvU6XNilhhhsM4Q  */
using BC = BCrypt.Net.BCrypt;
using Microsoft.AspNetCore.Http;

namespace FYP_Project.Controllers
{
    public class LogInController : Controller
    {
        public IActionResult Index()
        {
            return View("Index");
        }

        public IActionResult Register()
        {
            return View("Register");
        }

        public IActionResult CreateUpdate(PlayerViewModel viewModel)
        {

            viewModel.EditablePlayer.password = BC.HashPassword(viewModel.EditablePlayer.password);

            using (var db = DbHelper.GetConnection())
            {
                if (viewModel.EditablePlayer.PlayerID == null)
                {
                    viewModel.EditablePlayer.PlayerID = viewModel.Players.Count;
                    viewModel.EditablePlayer.UserType = "Player";
                    viewModel.EditablePlayer.Captain = 0;
                    viewModel.EditablePlayer.TeamID = null;
                    db.Insert<Player>(viewModel.EditablePlayer);
                    HttpContext.Session.SetString("emailAddress", viewModel.EditablePlayer.emailAddress);
                }
                else
                {
                    Player dbItem = db.Get<Player>(viewModel.EditablePlayer.PlayerID);
                    TryUpdateModelAsync<Player>(dbItem, "EditablePlayer");
                    db.Update<Player>(viewModel.EditablePlayer);
                }
            }
            return RedirectToAction("Index", "Home");
        }

        public IActionResult LogIn(PlayerViewModel viewModel)
        {
            foreach (var player in viewModel.Players)
            {
                if (player.emailAddress == viewModel.EditablePlayer.emailAddress)
                {
                    if (BC.Verify(viewModel.EditablePlayer.password, player.password) == true)
                    {
                        HttpContext.Session.SetString("emailAddress", viewModel.EditablePlayer.emailAddress);
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        return View("Index");
                    }
                }
            }
            return View("Index");
        }

        public IActionResult LogOut(PlayerViewModel viewModel)
        {
            HttpContext.Session.Clear();
            return View("Index");
        }

        public IActionResult ViewDetails(PlayerViewModel viewModel)
        {
            string email = HttpContext.Session.GetString("emailAddress");
            if (email == null)
            {
                return View("Index");
            }
            else
            {
                foreach (var player in viewModel.Players)
                {
                    if (email == player.emailAddress)
                    {
                        viewModel.EditablePlayer = player;
                    }
                }
                return View("Details", viewModel);
            }
        }

        public IActionResult Edit(int ID)
        {
            PlayerViewModel viewModel = new PlayerViewModel();
            viewModel.EditablePlayer = viewModel.Players.FirstOrDefault(x => x.PlayerID == ID);
            return View("Edit", viewModel);
        }
    }
}

FYP_Project/Views/LogIn/Details.cshtml
@{
    ViewData["Title"] = "Details";
    string imageURL = "Rocket-League-Emblem.png";
    string gameName = "tbd";
    string teamName = "tbd";
}
@model FYP_Project.ViewModels.PlayerViewModel
@foreach (var team in Model.Teams)
{
    if (Model.EditablePlayer.TeamID == team.TeamID)
    {
        imageURL = team.ImageURL;
        teamName = team.TeamName;
        foreach (var game in Model.Games)
        {
            if (team.GameID == game.GameID)
            {
                gameName = game.GameName;
            }
        }
    }
}

<!--html profile template found here: https://bbbootstrap.com/snippets/bootstrap-5-profile-card-animation-74461039-->
<section id="services" class="services section-bg">
    <div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
        <div class="card p-4">
            <div class=" image d-flex flex-column justify-content-center align-items-center">
                <button class="btn btn-secondary"> <img src="~/img/@imageURL" height="100" width="100" /></button>
                <span class="name mt-3">@Model.EditablePlayer.PlayerFirstName @Model.EditablePlayer.PlayerLastName</span> <span class="idd">@Model.EditablePlayer.GamerTag</span>
                <div class="d-flex flex-row justify-content-center align-items-center gap-2">
                    @foreach (var team in Model.Teams)
                    {
                        if (Model.EditablePlayer.TeamID == team.TeamID)
                        {
                            <span class="idd1"> @team.TeamName </span>
                        }
                    }
                </div>
                <div class=" d-flex mt-2">
                    <div class="btn1 btn-dark"><a href="/LogIn/Edit/@Model.EditablePlayer.PlayerID" style="color: #aeaeae;">Edit Profile</a></div>
                </div>
                @if (Model.EditablePlayer.TeamID == null)
                {
                    <div class=" d-flex mt-2">
                        <div class="btn1 btn-dark"><a asp-controller=Teams asp-action=SelectGame style="color: #aeaeae;">Join Team</a></div>
                    </div>
                    <div class=" d-flex mt-2">
                        <div class="btn1 btn-dark"><a asp-controller=Teams asp-action=Edit style="color: #aeaeae;">Create Team</a></div>
                    </div>
                }
                else
                {
                    <div class=" d-flex mt-2">
                        <div class="btn1 btn-dark"><a asp-controller=Teams asp-action=Index style="color: #aeaeae;">View Team</a></div>
                    </div>
                    <div class=" d-flex mt-2">
                        <div class="btn1 btn-dark"><a href="/Teams/Remove/@Model.EditablePlayer.PlayerID" style="color: #aeaeae;">Leave Team</a></div>
                    </div>
                }
                @if (Model.EditablePlayer.UserType == "Admin")
                {
                    <div class=" d-flex mt-2">
                        <div class="btn1 btn-dark"><a href="/LogIn/Edit/@Model.EditablePlayer.PlayerID" style="color: #aeaeae;">Create Fixture</a></div>
                    </div>
                }
                <div class="text mt-3">
                    <span>@Model.EditablePlayer.PlayerFirstName @Model.EditablePlayer.PlayerLastName is a @gameName player <br><br> They play for @teamName </span>
                </div>
            </div>
        </div>
    </div>
    <link rel="stylesheet" type="text/css" href="~/css/Profile.css" />
</section>

FYP_Project/Views/LogIn/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}
@model FYP_Project.ViewModels.PlayerViewModel

<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-xl-9 mx-auto">
                <div class="card flex-row my-5 border-0 shadow rounded-3 overflow-hidden">
                    <div class="card-img-left d-none d-md-flex">
                        <!-- Background image for card set in CSS! -->
                    </div>
                    <div class="card-body p-4 p-sm-5">
                        <h5 class="card-title text-center mb-5 fw-light fs-5">Edit Details</h5>

                        @using (var form = Html.BeginForm("CreateUpdate", "LogIn", FormMethod.Post))
                        {
                            @Html.HiddenFor(model => model.EditablePlayer.PlayerID)
                            @Html.HiddenFor(model => model.EditablePlayer.Captain)
                            @Html.HiddenFor(model => model.EditablePlayer.UserType)
                            @Html.HiddenFor(model => model.EditablePlayer.TeamID)


                            <div class="form-floating mb-3">
                                @Html.TextBoxFor(model => model.EditablePlayer.GamerTag, new { @class = "form-control", placeholder = "Username" })
                                <label for="floatingInputUsername">Username</label>
                            </div>

                            <div class="form-floating mb-3">
                                @Html.TextBoxFor(model => model.EditablePlayer.PlayerFirstName, new { @class = "form-control", placeholder = "First Name" })
                                <label for="floatingInputUsername">First Name</label>
                            </div>

                            <div class="form-floating mb-3">
                                @Html.TextBoxFor(model => model.EditablePlayer.PlayerLastName, new { @class = "form-control", placeholder = "Last Name" })
                                <label for="floatingInputUsername">Last Name</label>
                            </div>

                            <div class="form-floating mb-3">
                                @Html.TextBoxFor(model => model.EditablePlayer.emailAddress, new { @class = "form-control", placeholder = "Email Address" })
                                <label for="floatingInputEmail">Email address</label>
                            </div>

                            <div class="form-floating mb-3">
                                @Html.TextBoxFor(model => model.EditablePlayer.PlayerTelephone, new { @class = "form-control", placeholder = "Phone Number" })
                                <label for="floatingPassword">Phone Number</label>
                            </div>

                            <div class="form-floating mb-3">
                                @Html.TextBoxFor(model => model.EditablePlayer.PlayerAddress, new { @class = "form-control", placeholder = "Address" })
                                <label for="floatingPassword">Address</label>
                            </div>

                            <div class="form-floating mb-3">
                                @Html.TextBoxFor(model => model.EditablePlayer.TwitchName, new { @class = "form-control", placeholder = "Twitch Username" })
                                <label for="floatingPassword">Twitch Username</label>
                            </div>

                            <hr>

                            <div class="form-floating mb-3">
                                @Html.TextBoxFor(model => model.EditablePlayer.password, new { @class = "form-control", placeholder = "Password", type = "password" })
                                <label for="floatingPassword">Password</label>
                            </div>

                            <div class="form-floating mb-3">
                                <input type="password" class="form-control" id="floatingPasswordConfirm" placeholder="Confirm Password">
                                <label for="floatingPasswordConfirm">Confirm Password</label>
                            </div>

                            <div class="d-grid mb-2">
                                <button class="btn btn-lg btn-primary btn-login fw-bold text-uppercase" type="submit">Update</button>
                            </div>

                            @Html.ValidationSummary()
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <link rel="stylesheet" type="text/css" href="~/css/LogIn.css" />
</section>

FYP_Project/Views/LogIn/Index.cshtml
@{
    ViewData["Title"] = "LogIn";
}
@model FYP_Project.ViewModels.PlayerViewModel
<!-- code for login page found here: https://startbootstrap.com/snippets/login -->

<section id="services" class="services section-bg">
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5">
                        <h5 class="card-title text-center mb-5 fw-light fs-5">Sign In</h5>
                        @using (var form = Html.BeginForm("LogIn", "LogIn", FormMethod.Post))
                        {

                            <div class="form-floating mb-3">
                                @Html.TextBoxFor(model => model.EditablePlayer.emailAddress, new { @class = "form-control", placeholder = "Email Address" })
                                <label for="floatingInput">Email address</label>
                            </div>

                            <div class="form-floating mb-3">
                                @Html.TextBoxFor(model => model.EditablePlayer.password, new { @class = "form-control", placeholder = "Password", type = "password" })
                                <label for="floatingPassword">Password</label>
                            </div>

                            <div class="d-grid">
                                <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit">
                                    Sign
                                    in
                                </button>
                            </div>

                            <a class="d-block text-center mt-2 small" asp-controller=LogIn asp-action=Register>New User? Register</a>

                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <link rel="stylesheet" type="text/css" href="~/css/LogIn.css" />

</section>

FYP_Project/Views/LogIn/Register.cshtml
@{
    ViewData["Title"] = "Register";
}
@model FYP_Project.ViewModels.PlayerViewModel

<!-- code for register page found here: https://startbootstrap.com/snippets/registration-page -->

<section id="services" class="services section-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-xl-9 mx-auto">
                <div class="card flex-row my-5 border-0 shadow rounded-3 overflow-hidden">
                    <div class="card-img-left d-none d-md-flex">
                        <!-- Background image for card set in CSS! -->
                    </div>
                    <div class="card-body p-4 p-sm-5">
                        <h5 class="card-title text-center mb-5 fw-light fs-5">Register</h5>

                        @using (var form = Html.BeginForm("CreateUpdate", "LogIn", FormMethod.Post))
                        {
                            @Html.HiddenFor(model => model.EditablePlayer.PlayerID)

                            <div class="form-floating mb-3">
                                @Html.TextBoxFor(model => model.EditablePlayer.GamerTag, new { @class = "form-control", placeholder = "Username" })
                                <label for="floatingInputUsername">Username</label>
                            </div>

                            <div class="form-floating mb-3">
                                @Html.TextBoxFor(model => model.EditablePlayer.PlayerFirstName, new { @class = "form-control", placeholder = "First Name" })
                                <label for="floatingInputUsername">First Name</label>
                            </div>

                            <div class="form-floating mb-3">
                                @Html.TextBoxFor(model => model.EditablePlayer.PlayerLastName, new { @class = "form-control", placeholder = "Last Name" })
                                <label for="floatingInputUsername">Last Name</label>
                            </div>

                            <div class="form-floating mb-3">
                                @Html.TextBoxFor(model => model.EditablePlayer.emailAddress, new { @class = "form-control", placeholder = "Email Address" })
                                <label for="floatingInputEmail">Email address</label>
                            </div>

                            <hr>

                            <div class="form-floating mb-3">
                                @Html.TextBoxFor(model => model.EditablePlayer.password, new { @class = "form-control", placeholder = "Password", type = "password" })
                                <label for="floatingPassword">Password</label>
                            </div>

                            <div class="form-floating mb-3">
                                <input type="password" class="form-control" id="floatingPasswordConfirm" placeholder="Confirm Password">
                                <label for="floatingPasswordConfirm">Confirm Password</label>
                            </div>

                            <div class="d-grid mb-2">
                                <button class="btn btn-lg btn-primary btn-login fw-bold text-uppercase" type="submit">Register</button>
                            </div>

                            <a class="d-block text-center mt-2 small" asp-controller=LogIn asp-action=Index>Have an account? Sign In</a>

                            @Html.ValidationSummary()
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <link rel="stylesheet" type="text/css" href="~/css/LogIn.css" />

</section>